// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSM.Orleans")>]
[<assembly: AssemblyProductAttribute("FSM.Orleans")>]
[<assembly: AssemblyDescriptionAttribute("Strongly Typed State Machines for Orleans Actors - DSL/Parser/Code Generator/VSIX")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSM.Orleans"
    let [<Literal>] AssemblyProduct = "FSM.Orleans"
    let [<Literal>] AssemblyDescription = "Strongly Typed State Machines for Orleans Actors - DSL/Parser/Code Generator/VSIX"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
    let [<Literal>] AssemblyConfiguration = "Release"
