// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("FSM.Orleans.VSIX")]
[assembly: AssemblyProductAttribute("FSM.Orleans")]
[assembly: AssemblyDescriptionAttribute("Strongly Typed State Machines for Orleans Actors - DSL/Parser/Code Generator/VSIX")]
[assembly: AssemblyVersionAttribute("1.0")]
[assembly: AssemblyFileVersionAttribute("1.0")]
[assembly: AssemblyConfigurationAttribute("Release")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "FSM.Orleans.VSIX";
        internal const System.String AssemblyProduct = "FSM.Orleans";
        internal const System.String AssemblyDescription = "Strongly Typed State Machines for Orleans Actors - DSL/Parser/Code Generator/VSIX";
        internal const System.String AssemblyVersion = "1.0";
        internal const System.String AssemblyFileVersion = "1.0";
        internal const System.String AssemblyConfiguration = "Release";
    }
}
